#+TITLE: Philosophy of Statistics (2018 Spring)
#+OPTIONS: author:nil date:nil toc:nil num:nil
#+LaTeX_HEADER: \usepackage[margin=1.3in]{geometry}
#+LaTeX_HEADER: \renewcommand{\labelitemi}{--}


* Basic information
- Instructor: Jun Otsuka (=jotsuka@bun.kyoto-u.ac.jp=)
- Class: Tuesday 14:45-16:15 @ 9演
- Office hour: Tuesday 10:30-12:00 at L408, or by appointment.
- PandA: https://panda.ecs.kyoto-u.ac.jp/portal/site/2018-101-5143-004

* Theme
As a tool for deriving a conclusion from data, statistics plays a privileged role in today's science and can be called the "epistemology of science." This lecture introduces the contemporary statistical thinking/methods and explores epistemological as well as philosophical problems in scientific reasoning. 

* Goals
In this class students will learn 
1. the basics of the modern statistical thinking such as Bayesian inference and statistical testing, as well as their role in scientific reasoning.
2. philosophical assumptions and implications of these methodologies, especially regarding empiricism and realism.
3. the relationship between the modern statistical methods and issues in philosophical epistemology (e.g. the problem of induction, the internalist/externalist epistemology, etc.)


* Evaluation
- Quizzes (30%)
- Synopsis of the term paper (10%)
- Term paper (60%)

* Notes
- This class counts as a "seminar," but will be organized as a lecture.
- I understand some of you have worries about mathematical knowledge/skill. In this class, basic mathematical notions are explained in each lecture so that no prior knowledge of beyond high-school mathematics or statistics is required. Forgot even that? No problem, I'll explain it from scratch. However, you should try hard to review and digest the formal aspects after each class in order to understand following philosophical discussions. That will involve doing exercises and reading complementary texts.



* Plan

1. Introduction
2. Problems of induction
   - Statistics as epistemology (internalism/externalism/pragmatism and bayesianism/frequentism/model selection)
   - Statistics as inductive logic (Hume's problem, uniformity of nature)
3. A brief history of probability \& statistics
   - Quetelet's social physics
   - Galton, Pearson and positivism
4. The ABC of probability theory & statistics
   - Statistics, sample space, random variables, probability distribution
5. From descriptive statistics to inferential statistics
   - The descriptive statistics and positivism
   - The ontology of inferential statistics (probability model as the uniformity of nature, data/population dualism)
   - The epistemology of inferential statistics (sampling, statistical hypothesis, inference)
6. Bayesian statistics
   - The ABC of Bayesianism (Bayes' theorem, likelihood, prior, base rate fallacy)
   - Bayesian induction (induction, abduction, swamping of the priors)
   - Hierarchical Bayes and Bayesian networks
7. Bayes as internalist epistemology
   - Bayesianism as inductive logic
   - Bayesianism as internalism (coherence of briefs, the fundamental briefs and prior probabilities)
8. Critics of Bayesianism
   - Statistical criticisms (priors, catchall hypothesis)
   - Philosophical criticisms (internalism, psychologism)
   - Popper's falsificationism and its problem
9. Statistical tests 
   - The idea of statistical testing (null vs. alternative hypotheses, Type I/II errors, significance rate, power)
   - Practice of statistical testing (a coin example, the importance of sample size)
10. The frequentist philosophy 
    - Interpretation of tests (action and decision, hume's ``mind's habit'')
    - Reliabilism (belief forming process and the severity of a test)
    - Critics of frequentism
11. Estimation 
    - Maximum likelihood 
    - Regression (simple vs multiple regression, bias and variance)
12. Model selection
    - Model and complexity (curve fitting, truth vs. simplicity)
    - Akaike's theory (AIC, Ockham's rasor)
13. Machine Learning
    - Deep learning (its objectives, gradient descent method, regularization)
    - Induction in the era of big data (from truth to utility, pragmatism and pluralism)
14. Summary
    - Statistics and epistemology (epistemology of induction, three `ism's, statistics and philosophy)
    - What is knowledge? (Mach, Plato, and Bacon, knowledge and understanding)

* References
*** 歴史
  - デイヴィッド・サルツブルグ『統計学を拓いた異才たち』（日経ビジネス人文庫）
  - シャロン・バーチュ・マグレイン『異端の統計学ベイズ』（草思社）
  - イアン・ハッキング『偶然を飼いならす』（木鐸社）、『確率の出現』（慶應義塾大学出版会）
  - 芝村良『R.A.フィッシャーの統計理論』（九州大学出版会）

*** 統計基礎知識
  - 高橋信『マンガでわかる統計学』（オーム社）
  - デイビッド・ハンド『サイエンス・パレット 統計学』（丸善出版）
  - 三中信宏『みなか先生といっしょに 統計学の王国を歩いてみよう』（羊土社）

*** 哲学
  - 戸田山和久『知識の哲学』（産業図書）
  - エリオット・ソーバー『科学と証拠：統計学の哲学入門』（名古屋大学出版会）
  - Howson, C., & Urbach, P. (2006). /Scientific Reasoning/. Open Court Publishing.
  - Mayo, D. G. (1996). /Error and the Growth of Experimental Knowledge/. University of Chicago Press.
  - Romeijn, J. (2017). Philosophy of Statistics, in /Stanford Encyclopedia of Philosophy/, https://plato.stanford.edu/archives/spr2017/entries/statistics/



